[tool.poetry]
name = "rosetta-core"
version = "0.1.0"
description = "Core library associated with agentic workflows in Couchbase."
repository = "https://github.com/couchbaselabs/rosetta-core"
authors = [
    "Glenn Galvizo <glenn.galvizo@couchbase.com>",
    "Steve Yen <steve.yen@couchbase.com>",
    "Tanvi Johari <tanvi.johari@couchbase.com>"
]
readme = "README.md"
packages = [{ include = "rosetta" }]

[tool.poetry.urls]
Homepage = "https://couchbase.com"
Documentation = "https://docs.couchbase.com"
Repository = "https://github.com/couchbaselabs/rosetta-core"

[tool.poetry.scripts]
rosetta = "rosetta.cmd.main:main"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
click = "^8.1.7"
requests = "^2.32.3"
PyYAML = "^6.0.1"
semantic_version = "^2.10.0"
gitignore-parser = "^0.1.11"
GitPython = "^3.1.43"
cachetools = "^5.4.0"
scikit-learn = ">1.0.2"
numpy = ">1.13.3"
scipy = ">0.14.0"
sentence-transformers = "^3.0.1"
pydantic = "^2.8.2"
datamodel-code-generator = "^0.25.8"
fastapi = "^0.111.1"
Flask = "^3.0.3"
couchbase = "^4.3.0"
jinja2 = "^3.1.4"
openapi3-parser = "^1.1.17"
py-openapi-schema-to-json-schema = "^0.0.3"
tqdm = "^4.66.5"

# Note:
#   This dependency is purely for the StructuredTool (BaseTool) type.
#   All agent-frameworks we've seen to-date rely on BaseTool, so this feels like a sane dependency.
langchain-core = ">0.1.47"

[tool.pytest.ini_options]
markers = [
    "smoke: marks tests for running on each git-push"
]

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
