[tool.poetry]
name = "rosetta"
version = "0.1.0"
description = "User facing repository for all things rosetta (tooling around agent workflows)."
repository = "https://github.com/couchbaselabs/agentiq"
authors = [
    "Glenn Galvizo <glenn.galvizo@couchbase.com>"
]
readme = "README.md"

[tool.poetry.urls]
Homepage = "https://couchbase.com"
Documentation = "https://docs.couchbase.com"
Repository = "https://github.com/couchbaselabs/agentiq"

[tool.poetry.scripts]
rosetta = "rosetta.__main__:main"

[tool.poetry.dependencies]
python = "^3.11"
pydantic-settings = "^2.4.0"

#rosetta-core = { git = "git@github.com:couchbaselabs/rosetta-core.git" }
#rosetta-lc = { git = "git@github.com:couchbaselabs/rosetta-lc.git", optional = true }

# For developers that want to use a local version of Rosetta.
rosetta-core = { path = "/Users/tjohari/rosetta/rosetta-core", develop = true }
rosetta-lc = { path = "/Users/tjohari/rosetta/rosetta-lc", develop = true, optional = true }

[tool.poetry.extras]
langchain = ["rosetta-lc"]

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.0"

[tool.ruff]
line-length = 120
lint.select = ["F", "B", "I", "SIM"]
show-fixes = true

[tool.ruff.lint.isort]
no-sections = true
force-single-line = true
lines-between-types = 1
force-wrap-aliases = true
split-on-trailing-comma = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
