[tool.poetry]
name = "rosetta-lc"
version = "0.1.0"
description = "Collection of LangChain-specific classes and functions used with rosetta-core."
authors = [
  "Kush Khanna <kush.khanna@couchbase.com>"
]
readme = "README.md"
packages = [{include = "rosetta_lc"}]

[tool.poetry.urls]
Homepage = "https://couchbase.com"
Documentation = "https://docs.couchbase.com"
Repository = "https://github.com/couchbaselabs/rosetta-lc"

[tool.poetry.urls]
Homepage = "https://couchbase.com"
Documentation = "https://docs.couchbase.com"
Repository = "https://github.com/couchbaselabs/rosetta-lc"

[tool.poetry.dependencies]
python = "^3.11"
couchbase = "^4.3.0"
joblib = "^1.4.2"
langchain = "^0.2.12"
langchain-core = "^0.2.28"
langchain-openai = "^0.1.20"
pydantic = "2.8.2"
requests = "^2.32.3"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
