DEFAULT_SCOPE_PREFIX = "rosetta_catalog"
DEFAULT_AUDIT_SCOPE = "rosetta_logs"
DEFAULT_AUDIT_COLLECTION = "rosetta_session_logs"
DEFAULT_CATALOG_SCHEMA_VERSION = "0_0_0"
DEFAULT_FTS_PORT_NUMBER = "8094"

__all__ = [
    "DEFAULT_SCOPE_PREFIX",
    "DEFAULT_AUDIT_SCOPE",
    "DEFAULT_AUDIT_COLLECTION",
    "DEFAULT_CATALOG_SCHEMA_VERSION",
    "DEFAULT_FTS_PORT_NUMBER",
]
