DEFAULT_SCOPE_PREFIX = "rosetta_catalog"
DEFAULT_AUDIT_SCOPE = "rosetta_logs"
DEFAULT_AUDIT_COLLECTION = "rosetta_session_logs"
DEFAULT_CATALOG_SCHEMA_VERSION = "0.0.0"

__all__ = [
    "DEFAULT_SCOPE_PREFIX",
    "DEFAULT_AUDIT_SCOPE",
    "DEFAULT_AUDIT_COLLECTION",
    "DEFAULT_CATALOG_SCHEMA_VERSION",
]
