record_kind: prompt

# The name of the prompt must be a valid Python identifier (e.g., no spaces).
# This field is mandatory, and will be used when searching for prompts by name.
name: find_travel_routes

# A description of the prompt's purpose (e.g., where this prompt will be used).
# This field is mandatory, and will be used (indirectly) when performing semantic search for prompt.
description: Instructions on how to find routes between airports.

# As a supplement to the description similarity search, users can optionally specify search annotations.
# The values of these annotations MUST be strings (e.g., not 'true', but '"true"').
# This field is optional, and does not have to be present.
tools:
  # Tools can be specified using the same parameters found in Catalog.find("tool", ...).
  - name: find_direct_routes_between_airports
  - name: find_routes_with_one_layover

# As a supplement to the description similarity search, users can optionally specify search annotations.
# The values of these annotations MUST be strings (e.g., not 'true', but '"true"').
# This field is optional, and does not have to be present.
annotations:
  framework: "controlflow"

content:
  objective:
    Find a sequence of routes between the source airport and the destination airport.

  instructions:
    Try to find a direct routes first between the source airport and the destination airport.
    If there are no direct routes, then find a one-layover route.
    If there are no such routes, then try another source airport that is close.
