DEFAULT_SCOPE_PREFIX = "agent_catalog_catalog"
DEFAULT_AUDIT_SCOPE = "agent_catalog_logs"
DEFAULT_AUDIT_COLLECTION = "agent_catalog_session_logs"
DEFAULT_CATALOG_SCHEMA_VERSION = "0_0_0"
DEFAULT_HTTP_FTS_PORT_NUMBER = "8094"
DEFAULT_HTTPS_FTS_PORT_NUMBER = "18094"

__all__ = [
    "DEFAULT_SCOPE_PREFIX",
    "DEFAULT_AUDIT_SCOPE",
    "DEFAULT_AUDIT_COLLECTION",
    "DEFAULT_CATALOG_SCHEMA_VERSION",
    "DEFAULT_HTTP_FTS_PORT_NUMBER",
    "DEFAULT_HTTPS_FTS_PORT_NUMBER",
]
