DEFAULT_CATALOG_SCOPE = "agent_catalog"
DEFAULT_AUDIT_SCOPE = "agent_activity"
DEFAULT_AUDIT_COLLECTION = "raw_logs"
DEFAULT_CATALOG_SCHEMA_VERSION = "0_0_0"
DEFAULT_HTTP_FTS_PORT_NUMBER = "8094"
DEFAULT_HTTPS_FTS_PORT_NUMBER = "18094"
DEFAULT_ITEM_DESCRIPTION_MAX_LEN = 256
DEFAULT_MODEL_CACHE_FOLDER = ".model-cache"

__all__ = [
    "DEFAULT_CATALOG_SCOPE",
    "DEFAULT_AUDIT_SCOPE",
    "DEFAULT_AUDIT_COLLECTION",
    "DEFAULT_CATALOG_SCHEMA_VERSION",
    "DEFAULT_HTTP_FTS_PORT_NUMBER",
    "DEFAULT_HTTPS_FTS_PORT_NUMBER",
    "DEFAULT_MODEL_CACHE_FOLDER",
    "DEFAULT_ITEM_DESCRIPTION_MAX_LEN",
]
