import agentc_core.defaults

# Couchbase collection defaults.
DEFAULT_COUCHBASE_CACHE_SCOPE_NAME = agentc_core.defaults.DEFAULT_ACTIVITY_SCOPE
DEFAULT_COUCHBASE_CACHE_COLLECTION_NAME = "langchain_llm_cache"
DEFAULT_COUCHBASE_CACHE_INDEX_NAME = "langchain_llm_cache_index"
DEFAULT_COUCHBASE_CACHE_DDL_RETRY_ATTEMPTS = agentc_core.defaults.DEFAULT_CLUSTER_DDL_RETRY_ATTEMPTS
DEFAULT_COUCHBASE_CACHE_DDL_RETRY_WAIT_SECONDS = agentc_core.defaults.DEFAULT_CLUSTER_DDL_RETRY_WAIT_SECONDS

# Default score threshold for semantic cache.
DEFAULT_COUCHBASE_CACHE_INDEX_SCORE_THRESHOLD = 0.8

__all__ = [
    "DEFAULT_COUCHBASE_CACHE_SCOPE_NAME",
    "DEFAULT_COUCHBASE_CACHE_COLLECTION_NAME",
    "DEFAULT_COUCHBASE_CACHE_INDEX_NAME",
    "DEFAULT_COUCHBASE_CACHE_DDL_RETRY_ATTEMPTS",
    "DEFAULT_COUCHBASE_CACHE_DDL_RETRY_WAIT_SECONDS",
    "DEFAULT_COUCHBASE_CACHE_INDEX_SCORE_THRESHOLD",
]
