name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          cd docs
          pip install --upgrade pip
          pip install "sphinx==8.1.3" "sphinx-copybutton==0.5.2" "sphinx-hoverxref==1.4.1" \
                      "sphinx-click==6.0.0" "sphinx_rtd_theme" "myst_parser" \
                      "autodoc-pydantic==2.2.0" "sphinx-autobuild==2024.10.3" "furo==2024.8.6" \
                      "linkify-it-py==2.0.3"

      - name: Verify installation
        run: cd docs && pip show autodoc-pydantic

      - name: Sphinx build
        run: cd docs && rm -rf _build && sphinx-build source _build

      - name: List build files
        run: ls -R docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: github_pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true
