name: jenkins_pypi_publish
permissions:
  contents: read
  pull-requests: write

# Description:
# This GitHub Action triggers a Jenkins job to publish releases to test.pypi.

on:
  release:
    types: [ created ]

  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: version tag name

jobs:
  jenkins_pypi_publish:
    name: Publish to test.pypi on Jenkins
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        run: |
          # Trigger job and capture queue location
          queued_job_url=$(curl -X POST \
            "$JENKINS_BASE_URL/job/$JOB_NAME/buildWithParameters" \
            -d "PRODUCT=agent-catalog" \
            -d "VERSION=${VERSION}" \
            -d "PYPI_REPO=testpypi" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            -s -D - -o /dev/null | grep -i "location:" | cut -d' ' -f2 | tr -d '\r')

          echo "Queued job URL: ${queued_job_url}"

          # If queued_job_url begins with http, convert to https
          if [[ "$queued_job_url" =~ ^http: ]]; then
            queued_job_url="https:${queued_job_url:5}"
          fi
          echo "Queued job URL after conversion: ${queued_job_url}"

          echo "Waiting for build to start..."
          count=0
          while (( count <= 10 )); do
            is_blocked=$(curl --user "${JENKINS_USER}:${JENKINS_API_TOKEN}" \
              "${queued_job_url}/api/json" | jq -r .blocked)
            echo "Is blocked: ${is_blocked}"
            if [[ "$is_blocked" == "false" ]]; then
               # It might take a few seconds for jenkins job to transition from queued
               sleep 10
               echo "Checking build URL..."
               build_url=$(curl --user "${JENKINS_USER}:${JENKINS_API_TOKEN}" \
                 "${queued_job_url}/api/json" | jq -r .executable.url)
               echo "Build URL: ${build_url}"
               echo "It will take a while for AMI to be generated."
               echo "Please check progress at: ${build_url}"
               break
            fi
            count=$((count + 1))
            sleep 10
          done

          if [ -z "${build_url}" ]; then
            echo "Unable to determine URL for the jenkins run."
            echo "Check job status at: ${JENKINS_BASE_URL}/job/${JOB_NAME}"
          fi
        env:
          JENKINS_BASE_URL: "https://server.jenkins.couchbase.com"
          JENKINS_USER: ${{ secrets.SERVER_JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.SERVER_JENKINS_PAT }}
          VERSION: ${{ github.ref_name }}
          JOB_NAME: "PyPI-publish"
