name: tests
run-name: 👁️ ${{ github.actor }} has pushed a new commit!

on:
  push:
    # The PR process requires that these tests pass before merging, so running these again is unnecessary.
    branches-ignore:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  DocTests:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Python Poetry
        uses: mishaga/action-poetry@61dcf5051fb647e78e618f2b37482593b5b894c0
        with:
          python-version: "3.12"
          poetry-version: "latest"
          shell: "bash"

      - name: Install repository with Poetry
        run: |
          poetry install --with docs

      - name: Setup our package versions
        run: scripts/pre-build.sh

      - name: Build the documentation
        working-directory: docs
        run: |
          source $(poetry env info --path)/bin/activate
          make html

  SmokeTests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Verify toml files exist
        uses: thebinaryfelix/check-file-existence-action@fef222387dab4e18c8d7b379f209e8ef847b154d
        with:
          files: "pyproject.toml,\
            libs/agentc/pyproject.toml,\
            libs/agentc_core/pyproject.toml,\
            libs/agentc_cli/pyproject.toml,\
            libs/agentc_integrations/langchain/pyproject.toml,\
            libs/agentc_integrations/langgraph/pyproject.toml,\
            libs/agentc_integrations/llamaindex/pyproject.toml,\
            libs/agentc_testing/pyproject.toml"

      - name: Set up Python Poetry
        uses: mishaga/action-poetry@61dcf5051fb647e78e618f2b37482593b5b894c0
        with:
          python-version: "3.12"
          poetry-version: "latest"
          shell: "bash"

      - name: Run pre-commit checks
        uses: pre-commit/action@1b06ec171f2f6faa71ed760c4042bd969e4f8b43

      - name: Install repository with Poetry
        run: scripts/setup.sh dev

      - name: Export OPENAI API KEY secret
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - run: echo "🔥 Starting the smoke tests (🤞 please don't break!)."
      - name: Run agentc smoke tests
        run: scripts/test.sh smoke

      - run: echo "🍏 This job's status is ${{ job.status }}."

  ClickTests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Python Poetry
        uses: mishaga/action-poetry@61dcf5051fb647e78e618f2b37482593b5b894c0
        with:
          python-version: "3.12"
          poetry-version: "latest"
          shell: "bash"

      - name: Install repository with Poetry
        run: scripts/setup.sh dev

      - name: Export OPENAI API KEY secret
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - run: echo "🔥 Starting the click tests (🤞 please don't break!)."
      - name: Run agentc click tests
        run: scripts/test.sh click

      - run: echo "🍏 This job's status is ${{ job.status }}."

  SlowTests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Python Poetry
        uses: mishaga/action-poetry@61dcf5051fb647e78e618f2b37482593b5b894c0
        with:
          python-version: "3.12"
          poetry-version: "latest"
          shell: "bash"

      - name: Install repository with Poetry
        run: scripts/setup.sh dev

      - name: Export OPENAI API KEY secret
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - run: echo "🔥 Starting the slow tests (🤞 please don't break!)."
      - name: Run agentc slow tests
        run: scripts/test.sh slow

      - run: echo "🍏 This job's status is ${{ job.status }}."